version: "3.8"
services:
  api:
    depends_on:
      - db
    image: node:20
    # build:
    #   context: "./api"
    #   target: "base"
    volumes:
      - ./api:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: hello
    command: sh -c "npm install && npx nodemon index.js"
    ports:
      - "4000:4000"
    
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
      # - ./db/initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello
    ports:
      - "5432:5432"
    restart: always

  web:
    depends_on:
      - api
    image: node:20
    # build:
    #   context: "./web"
    #   target: "base"
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      API_BASEURL: http://api:4000
      PORT: 3000
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    
volumes:
  postgres-data:
